export const ALL_BATCH_REQUEST = 'ALL_BATCH_REQUEST'; 
export const ALL_BATCH_SUCCESS = 'ALL_BATCH_SUCCESS'; 
export const ALL_BATCH_FAIL = 'ALL_BATCH_FAIL'; 

export const BATCH_DETAILS_REQUEST = 'BATCH_DETAILS_REQUEST'; 
export const BATCH_DETAILS_SUCCESS = 'BATCH_DETAILS_SUCCESS'; 
export const BATCH_DETAILS_FAIL = 'BATCH_DETAILS_FAIL'; 
