export const ALL_BATCH_REQUEST = 'ALL_BATCH_REQUEST';
export const ALL_BATCH_SUCCESS = 'ALL_BATCH_SUCCESS';
export const ALL_BATCH_FAIL = 'ALL_BATCH_FAIL';

export const BATCH_DETAILS_REQUEST = 'BATCH_DETAILS_REQUEST';
export const BATCH_DETAILS_SUCCESS = 'BATCH_DETAILS_SUCCESS';
export const BATCH_DETAILS_FAIL = 'BATCH_DETAILS_FAIL';

export const CREATE_BATCH_REQUEST = 'CREATE_BATCH_REQUEST';
export const CREATE_BATCH_SUCCESS = 'CREATE_BATCH_SUCCESS';
export const CREATE_BATCH_FAIL = 'CREATE_BATCH_FAIL';
