export const ALL_EXAM_REQUEST = 'ALL_EXAM_REQUEST';
export const ALL_EXAM_SUCCESS = 'ALL_EXAM_SUCCESS';
export const ALL_EXAM_FAIL = 'ALL_EXAM_FAIL';

export const EXAM_DETAILS_REQUEST = 'EXAM_DETAILS_REQUEST';
export const EXAM_DETAILS_SUCCESS = 'EXAM_DETAILS_SUCCESS';
export const EXAM_DETAILS_FAIL = 'EXAM_DETAILS_FAIL';
