export const PAYMENT_INFO_REQUEST = 'PAYMENT_INFO_REQUEST';
export const PAYMENT_INFO_SUCCESS = 'PAYMENT_INFO_SUCCESS';
export const PAYMENT_INFO_FAIL = 'PAYMENT_INFO_FAIL';

export const CREATE_PAYMENT_STAT_REQUEST = 'CREATE_PAYMENT_STAT_REQUEST';
export const CREATE_PAYMENT_STAT_SUCCESS = 'CREATE_PAYMENT_STAT_SUCCESS';
export const CREATE_PAYMENT_STAT_FAIL = 'CREATE_PAYMENT_STAT_FAIL';

export const CONFIRM_PAYMENT_REQUEST = 'CONFIRM_PAYMENT_REQUEST'; 
export const CONFIRM_PAYMENT_SUCCESS = 'CONFIRM_PAYMENT_SUCCESS'; 
export const CONFIRM_PAYMENT_FAIL = 'CONFIRM_PAYMENT_FAIL'; 
