export const ALL_STUDENT_REQUEST = 'ALL_STUDENT_REQUEST';
export const ALL_STUDENT_SUCCESS = 'ALL_STUDENT_SUCCESS';
export const ALL_STUDENT_FAIL = 'ALL_STUDENT_FAIL';

export const STUDENT_DETAILS_REQUEST = 'STUDENT_DETAILS_REQUEST';
export const STUDENT_DETAILS_SUCCESS = 'STUDENT_DETAILS_SUCCESS';
export const STUDENT_DETAILS_FAIL = 'STUDENT_DETAILS_FAIL';

export const ADD_STUDENT_TO_BATCH_REQUEST = 'ADD_STUDENT_TO_BATCH_REQUEST'
export const ADD_STUDENT_TO_BATCH_SUCCESS = 'ADD_STUDENT_TO_BATCH_SUCCESS'
export const ADD_STUDENT_TO_BATCH_FAIL = 'ADD_STUDENT_TO_BATCH_FAIL'