export const SUBJECTS_REQUEST = 'SUBJECTS_REQUEST';
export const SUBJECTS_SUCCESS = 'SUBJECTS_SUCCESS';
export const SUBJECTS_FAIL = 'SUBJECTS_FAIL';

export const CREATE_SUBJECT_REQUEST = 'CREATE_SUBJECT_REQUEST';
export const CREATE_SUBJECT_SUCCESS = 'CREATE_SUBJECT_SUCCESS';
export const CREATE_SUBJECT_FAIL = 'CREATE_SUBJECT_FAIL';
